spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect  
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "12345678"
